# Generated by Django 3.1.7 on 2021-03-17 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imdb_id', models.CharField(max_length=250)),
                ('rotten_tomato', models.IntegerField()),
                ('budget', models.BigIntegerField()),
                ('overview', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ott',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.country')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeric', models.DecimalField(decimal_places=2, max_digits=4)),
                ('review', models.CharField(max_length=1000)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('overview', models.CharField(max_length=1000)),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_movie', models.BooleanField(default=False)),
                ('origin_country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.country')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.episode')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.language')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
            ],
        ),
        migrations.CreateModel(
            name='Mru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.episode')),
                ('rating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.rating')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user')),
            ],
        ),
        migrations.CreateModel(
            name='LangPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.language')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
            ],
        ),
        migrations.CreateModel(
            name='Genre_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.episode')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.genre')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show'),
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=250)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.episode')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
            ],
        ),
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=250)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.episode')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
            ],
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.episode')),
                ('ott_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ott')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
            ],
        ),
    ]
