# Generated by Django 3.1.7 on 2021-04-21 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OriginCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.country')),
            ],
        ),
        migrations.RemoveField(
            model_name='castmember',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='episode_id',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='show_id',
        ),
        migrations.RemoveField(
            model_name='crewmember',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='episode_of',
        ),
        migrations.RemoveField(
            model_name='available',
            name='episode_id',
        ),
        migrations.RemoveField(
            model_name='genre_of',
            name='episode_id',
        ),
        migrations.RemoveField(
            model_name='mru',
            name='episode_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='show',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='episode_id',
        ),
        migrations.AddField(
            model_name='show',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='budget',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='show',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='rotten_tomato',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movie.country'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='CastMember',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='CrewMember',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.AddField(
            model_name='origincountry',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show'),
        ),
        migrations.AddField(
            model_name='director',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person'),
        ),
        migrations.AddField(
            model_name='director',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show'),
        ),
        migrations.AddField(
            model_name='actor',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person'),
        ),
        migrations.AddField(
            model_name='actor',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show'),
        ),
    ]
